name: CI pipeline
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run model training smoke test
        run: ./batect smoke-test-model-training
      - name: Run API tests
        run: ./batect api-test

  train-model:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        run: ./batect train-model
      - name: Run model metrics tests
        run: ./batect model-metrics-test
    needs: run-tests
